### ISSUE TITLE
'softmaxAttn' (a nil value)?

### ISSUE THREAD

**Issue by codyhan** [OpenNMT/OpenNMT#229]
I trained a model without attention, when I run
```
th translate.lua -model ./checkpoints/demo-model_epoch13_4.69.t7 -src data/src-val.txt -output pred.txt -gpuid 1
```
It gives me error
```
[04/25/17 11:21:21 INFO] Using GPU(s): 1	
[04/25/17 11:21:21 INFO] Loading './checkpoints/demo-model_epoch13_4.69.t7'...	
[04/25/17 11:21:22 INFO] Model seq2seq trained on bitext	
/home/han/Software/torch/install/bin/luajit: ...install/share/lua/5.1/onmt/translate/DecoderAdvancer.lua:103: attempt to index field 'softmaxAttn' (a nil value)
stack traceback:
	...install/share/lua/5.1/onmt/translate/DecoderAdvancer.lua:103: in function 'update'
	...ch/install/share/lua/5.1/onmt/translate/BeamSearcher.lua:62: in function 'search'
	...orch/install/share/lua/5.1/onmt/translate/Translator.lua:273: in function 'translateBatch'
	...orch/install/share/lua/5.1/onmt/translate/Translator.lua:363: in function 'translate'
	translate.lua:110: in function 'main'
	translate.lua:196: in main chunk
	[C]: in function 'dofile'
	...ware/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x00406670
```
I have tried 
```
luarocks remove opennmt
luarocks make rocks/opennmt-scm-1.rockspec
```

**Comment by da03** [comment]
Sorry my bad, that's indeed a bug in beam search when attention layer is not present. Will fix it soon.

**Comment by guillaumekln** [comment]
No worries @da03, should be fixed now.

**Comment by da03** [comment]
Cool thanks!

**Comment by codyhan** [comment]
Thanks for your help @da03 @guillaumekln, but I still encountered a problem.

```
lab@lab:~/wzh/OpenNMT$ th translate.lua -model ./demo-model_epoch1_9.71.t7 -src data/src-val.txt -output pred.txt -gpuid 1
[04/27/17 10:56:15 INFO] Using GPU(s): 1	
[04/27/17 10:56:15 INFO] Loading './demo-model_epoch1_9.71.t7'...	
[04/27/17 10:56:16 INFO] Model seq2seq trained on bitext	
/home/lab/torch/install/bin/luajit: .../lab/torch/install/share/lua/5.1/onmt/translate/Beam.lua:128: invalid arguments: FloatTensor number CudaLongTensor 
expected arguments: [*FloatTensor*] FloatTensor index LongTensor
stack traceback:
	[C]: in function 'gather'
	.../lab/torch/install/share/lua/5.1/onmt/translate/Beam.lua:128: in function 'func'
	/home/lab/torch/install/share/lua/5.1/onmt/utils/Tensor.lua:12: in function 'recursiveApply'
	/home/lab/torch/install/share/lua/5.1/onmt/utils/Tensor.lua:7: in function 'selectBeam'
	.../lab/torch/install/share/lua/5.1/onmt/translate/Beam.lua:413: in function '_nextState'
	.../lab/torch/install/share/lua/5.1/onmt/translate/Beam.lua:401: in function '_nextBeam'
	...ch/install/share/lua/5.1/onmt/translate/BeamSearcher.lua:116: in function '_findKBest'
	...ch/install/share/lua/5.1/onmt/translate/BeamSearcher.lua:68: in function 'search'
	...orch/install/share/lua/5.1/onmt/translate/Translator.lua:275: in function 'translateBatch'
	...orch/install/share/lua/5.1/onmt/translate/Translator.lua:365: in function 'translate'
	translate.lua:110: in function 'main'
	translate.lua:196: in main chunk
	[C]: in function 'dofile'
	.../lab/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
	[C]: at 0x00406670
``` 

My model configuration is 
```
th train.lua -data data/demo-train.t7 -save_model demo-model -gpuid 1 -src_word_vec_size 300 -tgt_word_vec_size 300 -layers 4 -rnn_size 512 -residual -max_batch_size 512 -attention none -                fix_word_vecs_enc 1 -fix_word_vecs_dec 1 -end_epoch 1
```

**Comment by guillaumekln** [comment]
Thanks again for reporting. It is fixed.

**Comment by codyhan** [comment]
@guillaumekln, thanks now it works!!
